spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaojunming/SpringCloudTemplate.git
          searchPaths: config-resources
server:
  port: 1201
#注册为eureka服务来实现高可用
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
      #生产环境集群注册中心配置
      #defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
#对称性密钥。key一定要保护好,一旦暴露加密值就能被解密
encrypt:
  key: dyou
